### ISSUE TITLE
Mopidy-YouTube don't scrobble

### ISSUE THREAD

**Issue by liftarn** [mopidy/mopidy-scrobbler#13]
There seems to be no scrobbling of YouTube tracks. Not even a "Now playing".

**Comment by kingosticks** [comment]
Duplicate of https://github.com/mopidy/mopidy-scrobbler/issues/6

**Comment by kingosticks** [comment]
I tell a lie. not a duplicate.

**Comment by jodal** [comment]
No response in a month. Please reopen if you have more details to add.

**Comment by liftarn** [comment]
When I play a track from YouTube, for instance go to search and search just tracks fron YouTube. Play the track. When you view your page of Last.fm it says not that you are now playing the track nor does it say you have listened to it after it has finished playing. No scrobbling seem to take place.

**Comment by liftarn** [comment]
I found this in the log:
2015-03-29 00:34:37,426 - WARNING  Error submitting played track to Last.fm: trackNumber is not a valid integer: None
2015-03-29 00:34:37,712 - WARNING  Error submitting playing track to Last.fm: trackNumber is not a valid integer: None

**Comment by jodal** [comment]
What version of Mopidy-Scrobbler do you use? I think this was fixed in Mopidy-Scrobbler 1.1.1.

**Comment by liftarn** [comment]
Mopidy-Scrobbler: 1.1.0 from /usr/local/lib/python2.7/dist-packages
Mopidy-Youtube: 1.0.1 from /usr/local/lib/python2.7/dist-packages
so it wasn't fixed in the one I use?

**Comment by jodal** [comment]
Correct. `sudo pip install --upgrade mopidy-scrobbler` should fix it.
